server.port: 8082

spring:
  activemq:
    broker-url : tcp://localhost:61616
    user: admin
    password: admin

company.name: companyA
queue:
  request: company_request
  response: company_A_response