server.port: 8082

spring:
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME:bloom_client_A}
    username: ${DB_LOGIN:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
  activemq:
    broker-url : tcp://localhost:61616
    user: admin
    password: admin
  data:
    redis:
      database : 0
      host : localhost
      port: 6379
      password: 123456
      timeout : 60000


bloom:
  vector-size: 10000