server.port: 8084

spring:
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME:bloom_client_C}

company.name: company_C
queue:
  request: company_request
  response: company_C_response