server.port: 8085

spring:
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME:bloom_client_D}

company.name: company_D
queue:
  request: company_request
  response: company_D_response