server.port: 8086

spring:
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME:bloom_client_E}

company.name: company_E
queue:
  request: company_request
  response: company_E_response