server.port: 8082

spring:
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME:bloom_client_A}

company.name: company_A
queue:
  request: company_request
  response: company_A_response