server.port: 8083

spring:
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME:bloom_client_B}

company.name: company_B
queue:
  request: company_request
  response: company_B_response